/*CRIANDO O BANCO DE DADOS*/
CREATE DATABASE COMPUTER;

/*CONECTANDO AO BANCO DE DADOS*/
USE COMPUTER;

/*TABELA DE PLACA-MÃE*/
CREATE TABLE MBO (
    ID_MBO INT PRIMARY KEY AUTO_INCREMENT,
    MBO_MODEL VARCHAR(100) NOT NULL,
    MBO_CHIPSET VARCHAR(20) NOT NULL,
    PCIE_CONNECTIONS VARCHAR(50)
);

/*TABELA DE PROCESSADOR*/
CREATE TABLE CPU (
    ID_CPU INT PRIMARY KEY AUTO_INCREMENT,
    CPU_MODEL VARCHAR(100) NOT NULL,
    IGPU BOOLEAN NOT NULL,
    CORES INT NOT NULL,
    THREADS INT NOT NULL,
    FREQUENCY VARCHAR(20) NOT NULL,
    CACHE_L1 INT,
    CACHE_L2 INT,
    CACHE_L3 INT,
    CPU_CHIPSET VARCHAR(20) NOT NULL,
    TDP VARCHAR(10) NOT NULL,
    MAX_MEM_SUPPORT VARCHAR(20),
    ID_MBO INT,
    FOREIGN KEY (ID_MBO) REFERENCES MBO(ID_MBO)
);

/*TABELA DE CPU COOLER*/
CREATE TABLE COOLER (
    ID_COOLER INT PRIMARY KEY AUTO_INCREMENT,
    COOLER_MODEL VARCHAR(100) NOT NULL,
    COOLER_TYPE ENUM('AIRCOOLER', 'WATERCOOLER') NOT NULL,
    FAN_SIZE INT,
    RPM INT,
    FAN_NOISE FLOAT,
    AIRFLOW FLOAT,
    HEATPIPES INT,
    COMPATIBILITY VARCHAR(100),
    ID_CPU INT,
    FOREIGN KEY (ID_CPU) REFERENCES CPU(ID_CPU)
);

/*TABELA DE PLACA DE VÍDEO*/
CREATE TABLE GPU (
    ID_GPU INT PRIMARY KEY AUTO_INCREMENT,
    GPU_MODEL VARCHAR(100) NOT NULL,
    VRAM VARCHAR(10) NOT NULL,
    CORES INT NOT NULL,
    TMUS INT NOT NULL,
    ROPS INT NOT NULL,
    MEM_BANDWIDTH INTEGER NOT NULL
);

/*TABELA DE MEMÓRIA RAM*/
CREATE TABLE RAM (
    ID_RAM INT PRIMARY KEY AUTO_INCREMENT,
    RAM_MODEL VARCHAR(100) NOT NULL,
    CAPACITY INT NOT NULL,
    FREQUENCY VARCHAR(20) NOT NULL,
    TYPE ENUM('DDR3', 'DDR4', 'DDR5') NOT NULL
);

/*TABELA DE ARMAZENAMENTO*/
CREATE TABLE STORAGE (
    ID_STORAGE INT PRIMARY KEY AUTO_INCREMENT,
    STORAGE_MODEL VARCHAR(100) NOT NULL,
    CAPACITY INT NOT NULL,
    TYPE ENUM('HDD 3.5', 'HDD 2.5', 'SSHD', 'SSD') NOT NULL,
    INTERFACE ENUM('SATA', 'NVMe') NOT NULL
);

/*TABELA DE FONTE DE ALIMENTAÇÃO*/
CREATE TABLE PSU (
    ID_PSU INT PRIMARY KEY AUTO_INCREMENT,
    PSU_MODEL VARCHAR(100) NOT NULL,
    CABLES ENUM('NÃO MODULAR', 'SEMI MODULAR', 'FULL MODULAR') NOT NULL,
    SEAL_COMPLIANT ENUM('Bronze', 'Silver', 'Gold', 'Platinum', 'Titanium') NOT NULL,
    ACTIVE_PFC BOOLEAN NOT NULL,
    BIVOLT BOOLEAN NOT NULL
);

/*TABELA DE GABINETE*/
CREATE TABLE PC_CASE (
    ID_CASE INT PRIMARY KEY AUTO_INCREMENT,
    CASE_MODEL VARCHAR(100) NOT NULL,
    COMPATIBILITY VARCHAR(100),
    FORM_FACTOR ENUM('ITX', 'M-ATX', 'ATX', 'E-ATX') NOT NULL
);

